### ISSUE TITLE
CompletionException - IndexOutOfBoundsException thrown

### ISSUE THREAD

**Issue by mohlogan** [eclipse/lsp4jakarta#451]
While trying to recreate code action failure for issue https://github.com/OpenLiberty/liberty-tools-vscode/issues/247 i found following exception. 

May 22, 2023 11:00:47 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
java.util.concurrent.CompletionException: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
    at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
    at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
    at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
    at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
    at java.base/java.util.Objects.checkIndex(Unknown Source)
    at java.base/java.util.ArrayList.get(Unknown Source)
    at org.eclipse.lsp4jakarta.commons.SnippetRegistry.lambda$getCompletionItem$0(SnippetRegistry.java:196)
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
    at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
    at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
    at org.eclipse.lsp4jakarta.commons.SnippetRegistry.getCompletionItem(SnippetRegistry.java:215)
    at org.eclipse.lsp4jakarta.JakartaTextDocumentService.lambda$completion$2(JakartaTextDocumentService.java:122)
    ... 4 more

**Comment by cherylking** [comment]
How pervasive is this error? Does it cause anything to fail?

**Comment by mohlogan** [comment]
@cherylking I don't see any functionality affected. But i do see this error only on my windows-10 setup. It doesnt recreate on Mac. 

Frequency of the error in windows-10 : 4 to 5 times in 15 minutes of editing on jakarta specific java class.

**Comment by yeekangc** [comment]
Mohan will re-test with latest build from @TrevCraw.

**Comment by mohlogan** [comment]
I am unable to reproduce with latest 23.0.0-SNAPSHOT version of vscode binary.

**Comment by rumanaHaque** [comment]
In my testing with VSCode using the latest driver dated May 29th, liberty-dev-vscode-ext-23.0.6-SNAPSHOT.vsix, I was not able to recreate this exception.

**Comment by dshimo** [comment]
Curiously, I was able to recreate this on Mac with the 23.0.6-SNAPSHOT.
I used the jakarta-sample project, app name `jakarta-servlet`, found in this repo under jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects. I went to any file under the annotations dir. No changes were necessary.

Here I see some diagnostics and code completion works fine.
<img width="924" alt="image" src="https://github.com/eclipse/lsp4jakarta/assets/8934136/bf607843-97e5-4896-a984-de15a18f02bd">


Going up two levels and opening the dir from jakarta.jdt ...
Diagnostics vanish and triggering code completion produces this error.
<img width="1688" alt="image" src="https://github.com/eclipse/lsp4jakarta/assets/8934136/a942c07e-123d-4c34-bade-0eb872ece05a">

Text copy here:
```
May 31, 2023 3:37:03 PM org.eclipse.lsp4jakarta.JakartaTextDocumentService lambda$completion$1
SEVERE: Return LSP4Jakarta getContextBasedFilter() from client did not succeed: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request jakarta/java/classpath failed with message: java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.core.ICompilationUnit.getJavaProject()" because "unit" is null
May 31, 2023 3:37:03 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IndexOutOfBoundsException: Index 6 out of bounds for length 1
java.util.concurrent.CompletionException: java.lang.IndexOutOfBoundsException: Index 6 out of bounds for length 1
```

**Comment by TrevCraw** [comment]
@dshimo could you please post the whole stacktrace? The stacktrace looks a bit different from the original reported exception.

**Comment by dshimo** [comment]
I realize the approach was wildly different from mohlogan's and may be an entirely different issue as I was not able to reproduce [vscode#247](https://github.com/OpenLiberty/liberty-tools-vscode/issues/247)

Here's the stacktrace regardless,

```
SEVERE: Return LSP4Jakarta getContextBasedFilter() from client did not succeed: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request jakarta/java/classpath failed with message: java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.core.ICompilationUnit.getJavaProject()" because "unit" is null
Jun 01, 2023 9:51:47 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IndexOutOfBoundsException: Index 6 out of bounds for length 1
java.util.concurrent.CompletionException: java.lang.IndexOutOfBoundsException: Index 6 out of bounds for length 1
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.biApply(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: Index 6 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at org.eclipse.lsp4jakarta.commons.snippets.SnippetRegistry.lambda$getCompletionItem$1(SnippetRegistry.java:198)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.eclipse.lsp4jakarta.commons.snippets.SnippetRegistry.getCompletionItem(SnippetRegistry.java:217)
	at org.eclipse.lsp4jakarta.JakartaTextDocumentService.lambda$completion$3(JakartaTextDocumentService.java:145)
	... 8 more
```

**Comment by turkeylurkey** [comment]
We made a fix related to this, the one that fixed the package name and class name of a snippet. Could you ensure you are using the latest lsp4jakarta?
