### ISSUE TITLE
Quick fix does not show up on diagnostic hover

### ISSUE THREAD

**Issue by kathrynkodama** [eclipse/lsp4jakarta#60]
Quick fixes show up on hover when you first launch an Eclipse application:
![image](https://user-images.githubusercontent.com/26146482/100239369-560a8400-2eff-11eb-8dbb-cdd51aed7fb6.png)

Once a change is made, the quick fix no longer appears on the hover of the diagnostic: 
![image](https://user-images.githubusercontent.com/26146482/100239626-9e29a680-2eff-11eb-8760-ebaccaec2a56.png)

The quickfix is still accessible by clicking the warning on the left side bar, through the problems view, or right-clicking on the diagnostic and selecting "Quickfix" 
![image](https://user-images.githubusercontent.com/26146482/100239518-7df9e780-2eff-11eb-9458-d7de13c163f6.png)

**Comment by kathrynkodama** [comment]
Looks to be fixed with #26

**Comment by kathrynkodama** [comment]
Re-opening as this seems to be occurring with the latest from main
cc: @turkeylurkey

**Comment by mattbsox** [comment]
Here's what we're seeing at the moment on Eclipse `2022-06` with the latest from `main`.

The quick fix shows up initially when the file is first opened:
<img width="564" alt="Screen Shot 2022-09-14 at 2 44 31 PM" src="https://user-images.githubusercontent.com/6548952/190257509-63a5e8f8-e6e7-4b45-9b6b-f4db5cfcbb7a.png">

After a change is made the quick fix text shows `Computing...`
<img width="564" alt="Screen Shot 2022-09-14 at 2 45 01 PM" src="https://user-images.githubusercontent.com/6548952/190257791-adde91c6-43ce-4b0e-9c73-11a97c2aaaa6.png">

When the same diagnostic is re-hovered the correct quick fix is displayed:
<img width="564" alt="Screen Shot 2022-09-14 at 2 45 31 PM" src="https://user-images.githubusercontent.com/6548952/190257951-eb764e01-c1b9-487e-bcb8-2d4b8edd9fba.png">

Note that we only saw the `Computing...` message on Mac. Nothing is displayed for the quick fix message on Windows.

This seems to be the behavior on Eclipse versions `2022-03` and later.

We were able to reproduce the missing quick fix behavior on Eclipse versions `2021-12` and earlier.

**Comment by bensonnw** [comment]
On my windows machine, when quickfix is missing, there is an exception from Eclipse language server which will terminate the running process, not sure what we can do with that exception:

```
!MESSAGE InterruptedException
!STACK 0
java.lang.InterruptedException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:385)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at org.eclipse.lsp4e.operations.codeactions.LSPCodeActionMarkerResolution.checkMarkerResoultion(LSPCodeActionMarkerResolution.java:170)
	at org.eclipse.lsp4e.operations.codeactions.LSPCodeActionMarkerResolution.getResolutions(LSPCodeActionMarkerResolution.java:85)
	at org.eclipse.ui.internal.ide.registry.MarkerHelpRegistry.getResolutions(MarkerHelpRegistry.java:394)
	at org.eclipse.jdt.internal.ui.text.correction.JavaCorrectionProcessor.collectMarkerProposals(JavaCorrectionProcessor.java:318)
	at org.eclipse.jdt.internal.ui.text.correction.JavaCorrectionProcessor.collectProposals(JavaCorrectionProcessor.java:277)
	at org.eclipse.jdt.internal.ui.text.java.hover.ProblemHover$ProblemInfo.getMarkerAnnotationFixes(ProblemHover.java:154)
	at org.eclipse.jdt.internal.ui.text.java.hover.ProblemHover$ProblemInfo.computeCompletionProposals(ProblemHover.java:95)
	at org.eclipse.jdt.internal.ui.text.java.hover.ProblemHover$ProblemInfo.<init>(ProblemHover.java:74)
	at org.eclipse.jdt.internal.ui.text.java.hover.ProblemHover.createAnnotationInfo(ProblemHover.java:178)
	at org.eclipse.jdt.internal.ui.text.java.hover.AbstractAnnotationHover.getHoverInfo2(AbstractAnnotationHover.java:755)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:163)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:130)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavaEditorTextHoverProxy.getHoverInfo2(JavaEditorTextHoverProxy.java:89)
	at org.eclipse.jface.text.TextViewerHoverManager$1.run(TextViewerHoverManager.java:155)

```

**Comment by TrevCraw** [comment]
@bensonnw is no longer seeing the exception reported on Sep 15
@mattbsox to attempt to recreate the issue on Mac

**Comment by mattbsox** [comment]
Still seeing the same behavior as before.

**Comment by kathrynkodama** [comment]
Closing as with the latest "Computing" is shown when the quick-fix is still loading
